### ISSUE TITLE
Error: Tibble columns must have compatible sizes

### ISSUE THREAD

**Issue by Rikkiff** [grimbough/FITfileR#17]
Dear Mike, 
I just completed the Danish Championship in trail and was excited to review the data. However, the FIT file is corrupt, and hence, I installed your package in the hope of being able the identify the file error. However, when attempting to read the file with your function "readFitFile()" I get the error message: "Error: Tibble columns must have compatible sizes". I guess this could be the reason for the file being corrupt in the first place. I was wondering if they is a way for my to read the file anyway, perhaps by somehow filling out the too short coumns with "NAs". 

Sorry that I am posting the question under "Issues" even though my problem is not an issue related to your code. And ålease ignore me, if you find my question inappropriate.  

Best regards from a fellow molecular biologist, 
Rikki Franklin Frederiksen
Denmark

**Comment by grimbough** [comment]
Hi Rikki,

Are you willing to share the file with me? My email address can be found in the DESCRIPTION file if you don't want to post it here.

It certainly sounds like there's something odd with the file. However the good news is that because FIT files are generally written as the data are being received, even if there's a corruption somewhere there may be some useable data too. Unfortunately that error message could be coming from a number of places & I'm not sure I can provide much help without the specific file to work with.

**Comment by Rikkiff** [comment]
Hi again Mike, 

The FIT file size is relatively large, so there must be some data hiding in there : ). I was trying to attach the FIT file here, but file type is not supported, so I well send it to your mail. Thanks a lot for the help Mike. 

Best, 
Rikki

**Comment by Rikkiff** [comment]
Hi Mike
I have attached the file. Thanks a lot.
Best,
Rikki

**Comment by grimbough** [comment]
I don't think that's worked as I don't see any attached files.  You can either email me directly i.e a new email rather than replying to this Github issue email, or you can rename the FIT file to a ZIP file and Github will happily let you upload it here.
