### ISSUE TITLE
readFitFile memory size

### ISSUE THREAD

**Issue by Biomiha** [grimbough/FITfileR#7]
Hi Mike,

Firstly I want to say I'm loving the package and the vignette is also very useful. I was just wondering if you had any idea why the memory size of the `FitFile-class` when read into memory was so big? 
Reading in a 60m club ride fit file from my Wahoo ELEMNT bolt that occupies ~450kb on disk took about 400 secs on my MacBook Pro and grew to a staggering ~180MB in RAM for ~14000 data points. 
The Garmin SDK FitCSV tool converts the same file to a 4.5MB .csv file on disk (~15MB in RAM in RStudio) in a couple of seconds. 
I understand .fit is a binary file. Would there be a benefit in a simple wrapper function that just parses out the equivalent of the csv file?

Thanks.

**Comment by grimbough** [comment]
Thanks for the feedback, I'm glad you're finding it useful.  The performance characteristics you've seen are down to some of the design choices I made when creating the package.   The FIT format consists of loads of 'messages' which either carry a measurement by the device (a data message), or describe the specific format of a data message (a definition message). I though it would be elegant to have an S4 class for the file (the `FitFile-class`) that is comprised of more S4 objects of class `FitDefinitionMessage` and `FitDataMessage` - essentially mirroring the file format in code.

However I didn't appreciate creating all these distinct objects comes with quite an overhead, and most of the run time is spent calling `new()` inside the reading functions.  I'm surprised it takes 400 seconds, for me it takes 3 seconds to read ~2500 records in the fenix6 example file.  However the FIT format is super flexible and I've never read a file from a Wahoo device.  If you'd be willing to send it to me, I'll see if there's somewhere else it's slowing down.

Regarding the memory usage, is that reported by the RStudio environment browser?  I'd be interested to see the output from the function `pryr::object_size()`.  Because of it's structure, a typical `FitFile` object contains many identical `FitDefinitionMessage` objects.  However I try to reuse the same object in memory when possible, rather than creating many copies.  Both RStudio and `object.size()` don't seem to recognise this and report higher memory usage than `pryr::object_size()`, which I think it more accurate e.g.

```r
library(FITfileR)
fenix6_file <- system.file("extdata", "Activities", "garmin-fenix6-swim.fit", 
                           package = "FITfileR")
system.time( fenix6 <- readFitFile(fenix6_file) )
#>    user  system elapsed 
#>   3.053   0.028   3.082

print(object.size(fenix6), units = "MB")
#> 15.3 Mb
pryr::object_size(fenix6)
#> 3.34 MB
## compare_size() gives a direct comparison in bytes
pryr::compare_size(fenix6)
#>     base     pryr 
#> 16059784  3340312 
```

**Comment by Biomiha** [comment]
So running `pryr::object_size` does make a difference, i.e. it's down to ~30MB, however obviously the elapsed time is still almost the same. 
    
    system.time(Fit_file_parsed <- readFitFile("2020-11-07-094936-ELEMNT BOLT 471A-18-0.fit"))
       user  system elapsed 
    357.124   1.293 360.434 

    print(object.size(Fit_file_parsed), units = "MB")
    155.6 Mb
    pryr::object_size(Fit_file_parsed)
    30.2 MB
    pryr::compare_size(Fit_file_parsed)
         base      pryr 
    163207216  30227648 

I can share the file. Perhaps I'd rather send it to a personal email than GitHub given that it's got 3.5hrs worth of my heart rate etc... :)

**Comment by grimbough** [comment]
Sure, my email is in the DESCRIPTION file.

**Comment by grimbough** [comment]
Thanks for the file.  I can confirm there's a problem with the code - it took 15 minutes to read on my laptop!

You file has lots of 'developer data' which means Wahoo want to store some extra fields that aren't in the standard FIT specification.  I had some test files with a single developer data record, so the code worked, but it was horribly slow with 11,000 records that have this.  I'll makes some changes to try and improve the read performance.

**Comment by Biomiha** [comment]
Thanks for the update Mike. I've got smaller files as well for shorter distances (~2.5m, 5m, 15m, 25m, etc...) so let me know if you need anything. Or if you need any help debugging the code.

**Comment by grimbough** [comment]
I've made some significant changes that should improve this situations.  Reading your file is now acceptable (if still not exactly instant) and the resulting object is a bit smaller too.

```r
> system.time(wahoo <- readFitFile("~/Downloads/2020-11-07-094936-ELEMNT BOLT 471A-18-0.fit"))
   user  system elapsed 
 22.820   0.025  22.862 
> pryr::object_size(wahoo)
23.2 MB
```

**Comment by Biomiha** [comment]
Awesome! Yes, this completes in <8secs for me. 
The object size according to the `object.size` function is ~124Mb and ~23Mb is you ask `pryr`.

Thanks Mike!
